Задание 1**
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
  - оценка 2 и меньше - низкий рейтинг
  - оценка 4 и меньше - средний рейтинг
  - оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [55]:
import pandas as pd

rate_stats = pd.read_csv('ratings.csv')

rategroup = rate_stats.groupby('movieId').agg({'rating': 'mean'})

def rate_films(rategroup):
    if rategroup['rating'] <= 2:
        rate = 'низкий рейтинг'
    elif 4.5 > rategroup['rating'] > 2:
        rate = 'средний рейтинг'
    else:
        rate = 'высокий рейтинг'
    return rate

rategroup['class'] = rategroup.apply(rate_films, axis=1)

movies = pd.read_csv('movies.csv')
tabnew = pd.merge(movies, rategroup, on ='movieId') 
tabnew.head()

,movieId,title,genres,rating,class
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,3.920930,средний рейтинг
1,2,Jumanji (1995),Adventure|Children|Fantasy,3.431818,средний рейтинг
2,3,Grumpier Old Men (1995),Comedy|Romance,3.259615,средний рейтинг
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,2.357143,средний рейтинг
4,5,Father of the Bride Part II (1995),Comedy,3.071429,средний рейтинг

**Задание 2**
Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце 'region' пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим 'undefined'.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

geo_data = {

    'Центр': ['москва', 'тула', 'ярославль'],

    'Северо-Запад': ['петербург', 'псков', 'мурманск'],

    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']

}

Результат классификации запишите в отдельный столбец region.

In [103]:
geo_data = {
'Центр': ['москва', 'тула', 'ярославль'],
'Северо-Запад': ['петербург', 'псков', 'мурманск'],
'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

kw = pd.read_csv('keywords.csv')

def geosort(kw):
    reg = 'undefined'
    for w in kw['keyword'].split(' '):
        for key, value in geo_data.items():
            if w in value:
                reg = key
                break         
    return reg
    
kw['region'] = kw.apply(geosort, axis=1)

kw.to_csv('keywords_geo.csv', encoding = 'utf-8') 
kw.head()

         keyword     shows     region
0             вк  64292779  undefined
1  одноклассники  63810309  undefined
2          порно  41747114  undefined
3           ютуб  39995567  undefined
4      вконтакте  21014195  undefined

**Задание 3 (бонусное)**
Есть мнение, что "раньше снимали настоящее кино, не то что сейчас". Ваша задача проверить это утверждение, используя файлы с рейтингами фильмов из прошлого домашнего занятия (файл ratings.csv из базы https://grouplens.org/datasets/movielens). Т. е. проверить верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

При этом мы не будем затрагивать субьективные факторы выставления этих рейтингов, а пройдемся по следующему алгоритму:

1. В переменную years запишите список из всех годов с 1950 по 2010.

2. Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска. Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:
  - для каждой строки пройдите по всем годам списка years
  - если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска
  - если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год

3. Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец 'year'

4. Посчитайте средний рейтинг всех фильмов для каждого значения столбца 'year' и отсортируйте результат по убыванию рейтинга